from typing import Protocol, runtime_checkable

from mcp_core.adapters.base import DataAdapter

from gse_mcp.models import Equity, HistoryEntry, MarketSummary, Stock


@runtime_checkable
class GSEDataAdapter(DataAdapter, Protocol):
    """GSE-specific adapter contract."""

    async def get_live_prices(self) -> list[Stock]: ...
    async def get_stock_price(self, symbol: str) -> Stock | None: ...
    async def get_stock_history(self, symbol: str, days: int) -> list[HistoryEntry]: ...
    async def get_market_summary(self) -> MarketSummary | None: ...
    async def fetch_equities(self) -> list[Equity]: ...
    async def get_equity(self, symbol: str) -> Equity | None: ...
